*&---------------------------------------------------------------------*
*& Include          ZARV4_R_GET_INFORMATION_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK bn1 WITH FRAME TITLE TEXT-t01.

  PARAMETERS: s_tr_d LIKE gv_date,
              p_lang TYPE spras.
  SELECTION-SCREEN SKIP.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: p_spec RADIOBUTTON GROUP gr1 DEFAULT 'X' USER-COMMAND spec.
    SELECTION-SCREEN COMMENT 3(20) TEXT-t11.
    PARAMETERS: p_rem_n RADIOBUTTON GROUP gr1.
    SELECTION-SCREEN COMMENT 26(20) TEXT-t12.
    PARAMETERS: p_work RADIOBUTTON GROUP gr1.
    SELECTION-SCREEN COMMENT 49(20) TEXT-t13.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bn1.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK bn2 WITH FRAME TITLE TEXT-t02.
  SELECTION-SCREEN BEGIN OF BLOCK bn21 WITH FRAME TITLE TEXT-t21.
    PARAMETERS: p_fm_id LIKE gv_nom_id MATCHCODE OBJECT zarv4_sh_fg MODIF ID gr2.
  SELECTION-SCREEN END OF BLOCK bn21.
SELECTION-SCREEN END OF BLOCK bn2.

SELECTION-SCREEN BEGIN OF BLOCK bn3 WITH FRAME TITLE TEXT-t03.
  SELECTION-SCREEN BEGIN OF BLOCK bn31 WITH FRAME TITLE TEXT-t31.
    SELECT-OPTIONS: p_no_id FOR gv_nom_id MATCHCODE OBJECT zarv4_sh_all_nom MODIF ID gr3.
    SELECTION-SCREEN SKIP.

    PARAMETERS: p_raw_m AS CHECKBOX USER-COMMAND r_raw_m MODIF ID gr3.
    PARAMETERS: p_in_m AS CHECKBOX USER-COMMAND r_in_m MODIF ID gr3.
    PARAMETERS: p_ex_m AS CHECKBOX USER-COMMAND r_ex_m MODIF ID gr3.
    PARAMETERS: p_fg_m AS CHECKBOX USER-COMMAND r_ex_m MODIF ID gr3.
  SELECTION-SCREEN END OF BLOCK bn31.
SELECTION-SCREEN END OF BLOCK bn3.

SELECTION-SCREEN BEGIN OF BLOCK bn4 WITH FRAME TITLE TEXT-t04.
  SELECTION-SCREEN BEGIN OF BLOCK bn41 WITH FRAME TITLE TEXT-t41.
    SELECT-OPTIONS: p_emp  FOR gv_emp MATCHCODE OBJECT zarv4_sh_rp MODIF ID gr4.
    SELECT-OPTIONS: p_empm FOR gv_emp MATCHCODE OBJECT zarv4_sh_rp MODIF ID gr4.
    SELECTION-SCREEN SKIP.

    PARAMETERS: p_act AS CHECKBOX USER-COMMAND r_act MODIF ID gr4.
  SELECTION-SCREEN END OF BLOCK bn41.
SELECTION-SCREEN END OF BLOCK bn4.

*Data definition
INITIALIZATION.
  s_tr_d = sy-datum.
  p_lang = sy-langu.
  p_raw_m = 'X'.
  p_in_m  = 'X'.
  p_ex_m  = 'X'.
  p_fg_m  = 'X'.
  p_act   = 'X'.
